language: python
python: #versiones de Python que se van a testear
  - "3.6"
  - "3.6.8" 
  - "3.7"
  - "3.8"
  - "3.8-dev"

install: #instalamos dependencias
  - pip install -r requirements.txt
  - pip install codecov #instalamos codecov para mandar los test de cobertura

script: 
  - invoke test #ejecutamos los test unitarios
  - invoke coverage

after_success:
  - codecov
